######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 24 22:16:59 2013
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwin.h \
    mlabel.h
SOURCES += main.cpp mainwin.cpp

FORMS += \
    mainwin.ui \
    tmedit.ui

RESOURCES += \
    resrs.qrc
